application:
  name: "Demo Server"
  version: "1.0.0"

netty:
  port: 8080
  readerIdleTime: 0
  witerIdleTime: 0
  allIdleTime: 60
  byteOrder: "true"
  autoRead: "true"
  tcpNoDelay: "true"
  soRcvBuf: 1048576
  soSndBuf: 1048576
  connectTimeOut: 10000
  keepAlive: "false"

thread:
  poolSizeMultiplier: 2
  maxPoolSize: 10
  queueCapacity: 500
  keepAlive: 60


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/demo"
    username: "root"
    password: ""
    driver-class-name: "com.mysql.cj.jdbc.Driver"
