application:
  name: "Demo Server"
  version: "1.0.0"

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/demo?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    username: "demo"
    password: "demo"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

netty:
  port: 8080
  readerIdleTime: 0
  witerIdleTime: 0
  allIdleTime: 60
  byteOrder: "true"
  autoRead: "true"
  tcpNoDelay: "true"
  soRcvBuf: 1048576
  soSndBuf: 1048576
  connectTimeOut: 10000
  keepAlive: "false"

thread:
  poolSizeMultiplier: 2
  maxPoolSize: 10
  queueCapacity: 500
  keepAliveSeconds: 60

mybatis:
  mapper-locations: "classpath*:mapper/*.xml"
  type-aliases-package: "com.demo.packet"
  configuration:
    map-underscore-to-camel-case: "true"
    cache-enabled: "true"


